/*
 * Zplat API
 *
 * This is a zplat api-server api.
 *
 * API version: 1.0.0
 * Contact: saltbo@foxmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type ModelSubsystem struct {
	AccessKey string `json:"access_key,omitempty"`
	AccessSecret string `json:"access_secret,omitempty"`
	Address string `json:"address,omitempty"`
	Created string `json:"created,omitempty"`
	Id int32 `json:"id,omitempty"`
	Intro string `json:"intro,omitempty"`
	Name string `json:"name,omitempty"`
	Updated string `json:"updated,omitempty"`
}
