/*
 * Zplat API
 *
 * This is a zplat api-server api.
 *
 * API version: 1.0.0
 * Contact: saltbo@foxmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type AllOfinlineResponse200Data struct {
	List  []ModelSubsystem `json:"list,omitempty"`
	Total int32            `json:"total,omitempty"`
}
