/*
 * Zplat API
 *
 * This is a zplat api-server api.
 *
 * API version: 1.0.0
 * Contact: saltbo@foxmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type BindBodyUserPassword struct {
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}
