/*
 * Zplat API
 *
 * This is a zplat api-server api.
 *
 * API version: 1.0.0
 * Contact: saltbo@foxmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type InlineResponse2002 struct {
	Data *AllOfinlineResponse2002Data `json:"data,omitempty"`
	HttputilJSONResponse *HttputilJsonResponse `json:"httputil.JSONResponse,omitempty"`
}
